CREATE TABLE IF NOT EXISTS "club_points_rule_version" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "version_no" varchar(64) NOT NULL,
  "name" varchar(128) NOT NULL,
  "status" tinyint NOT NULL,
  "publicity_time" datetime NULL,
  "effective_time" datetime NOT NULL,
  "published_time" datetime NULL,
  "disabled_time" datetime NULL,
  "summary" varchar(1024) NULL,
  "content" text NULL,
  "attachment_snapshot_json" longtext NULL,
  "remark" varchar(512) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_rule_version_no" ON "club_points_rule_version" ("version_no");
CREATE INDEX IF NOT EXISTS "idx_club_points_rule_version_status_effective" ON "club_points_rule_version" ("status", "effective_time");

CREATE TABLE IF NOT EXISTS "club_points_rule_item" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "rule_version_id" bigint NOT NULL,
  "item_code" varchar(128) NOT NULL,
  "item_name" varchar(128) NOT NULL,
  "item_type" tinyint NOT NULL,
  "category" tinyint NOT NULL,
  "min_points" int NULL,
  "max_points" int NULL,
  "default_points" int NULL,
  "int_value" int NULL,
  "decimal_value" decimal(18,6) NULL,
  "text_value" varchar(512) NULL,
  "json_value" longtext NULL,
  "status" tinyint NOT NULL,
  "sort" int NOT NULL,
  "remark" varchar(512) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_rule_item_version_code" ON "club_points_rule_item" ("rule_version_id", "item_code");
CREATE INDEX IF NOT EXISTS "idx_club_points_rule_item_code_status" ON "club_points_rule_item" ("item_code", "status");

CREATE TABLE IF NOT EXISTS "club_points_rule_publish_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "rule_version_id" bigint NOT NULL,
  "action" tinyint NOT NULL,
  "operator_user_id" bigint NOT NULL,
  "operation_time" datetime NOT NULL,
  "reason" varchar(512) NULL,
  "before_json" longtext NULL,
  "after_json" longtext NULL,
  "audit_log_id" bigint NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_rule_publish_version_time" ON "club_points_rule_publish_record" ("rule_version_id", "operation_time");

CREATE TABLE IF NOT EXISTS "club_points_club" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "code" varchar(64) NOT NULL,
  "name" varchar(128) NOT NULL,
  "status" tinyint NOT NULL,
  "description" varchar(2048) NULL,
  "contact_text" varchar(256) NULL,
  "cover_file_id" bigint NULL,
  "sort" int NOT NULL,
  "disabled_time" datetime NULL,
  "disabled_reason" varchar(512) NULL,
  "remark" varchar(512) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_club_code" ON "club_points_club" ("code");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_club_name" ON "club_points_club" ("name");
CREATE INDEX IF NOT EXISTS "idx_club_points_club_status_sort" ON "club_points_club" ("status", "sort");

CREATE TABLE IF NOT EXISTS "club_points_club_member" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "club_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "dept_id_snapshot" bigint NULL,
  "user_name_snapshot" varchar(128) NOT NULL,
  "dept_name_snapshot" varchar(128) NULL,
  "mobile_snapshot" varchar(64) NULL,
  "club_code_snapshot" varchar(64) NOT NULL,
  "club_name_snapshot" varchar(128) NOT NULL,
  "status" tinyint NOT NULL,
  "join_time" datetime NOT NULL,
  "leave_time" datetime NULL,
  "leave_reason_type" tinyint NULL,
  "leave_reason" varchar(512) NULL,
  "operator_user_id" bigint NULL,
  "active_unique_key" varchar(160) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_club_member_active" ON "club_points_club_member" ("active_unique_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_club_member_club_status" ON "club_points_club_member" ("club_id", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_club_member_user_status" ON "club_points_club_member" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_club_leader" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "club_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "status" tinyint NOT NULL,
  "assigned_time" datetime NOT NULL,
  "removed_time" datetime NULL,
  "assigned_by" bigint NOT NULL,
  "removed_by" bigint NULL,
  "reason" varchar(512) NOT NULL,
  "club_name_snapshot" varchar(128) NOT NULL,
  "user_name_snapshot" varchar(128) NOT NULL,
  "active_unique_key" varchar(160) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_club_leader_active" ON "club_points_club_leader" ("active_unique_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_club_leader_club_status" ON "club_points_club_leader" ("club_id", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_club_leader_user_status" ON "club_points_club_leader" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_activity" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "club_id" bigint NOT NULL,
  "club_code_snapshot" varchar(64) NOT NULL,
  "club_name_snapshot" varchar(128) NOT NULL,
  "title" varchar(256) NOT NULL,
  "location" varchar(256) NULL,
  "description" text NULL,
  "cover_file_id" bigint NULL,
  "level" tinyint NOT NULL,
  "status" tinyint NOT NULL,
  "start_time" datetime NOT NULL,
  "end_time" datetime NOT NULL,
  "registration_deadline" datetime NOT NULL,
  "cancel_deadline_time" datetime NULL,
  "checkin_start_time" datetime NOT NULL,
  "checkin_end_time" datetime NOT NULL,
  "checkout_mode" tinyint NOT NULL,
  "checkout_start_time" datetime NOT NULL,
  "checkout_end_time" datetime NOT NULL,
  "current_config_version_id" bigint NULL,
  "creator_user_id" bigint NOT NULL,
  "submit_time" datetime NULL,
  "publish_time" datetime NULL,
  "cancel_time" datetime NULL,
  "cancel_reason" varchar(512) NULL,
  "snapshot_json" longtext NULL,
  "remark" varchar(512) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_club_status_start" ON "club_points_activity" ("club_id", "status", "start_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_status_start" ON "club_points_activity" ("status", "start_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_end_status" ON "club_points_activity" ("end_time", "status");

CREATE TABLE IF NOT EXISTS "club_points_activity_review_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "activity_id" bigint NOT NULL,
  "reviewer_user_id" bigint NOT NULL,
  "result" tinyint NOT NULL,
  "reason" varchar(512) NULL,
  "review_time" datetime NOT NULL,
  "activity_snapshot_json" longtext NOT NULL,
  "audit_log_id" bigint NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_review_activity_time" ON "club_points_activity_review_record" ("activity_id", "review_time");

CREATE TABLE IF NOT EXISTS "club_points_activity_point_config_version" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "activity_id" bigint NOT NULL,
  "version_no" int NOT NULL,
  "level" tinyint NOT NULL,
  "base_points" int NOT NULL,
  "full_extra_points" int NOT NULL,
  "rule_version_id" bigint NOT NULL,
  "base_rule_item_id" bigint NULL,
  "full_rule_item_id" bigint NULL,
  "effective_time" datetime NOT NULL,
  "created_reason" varchar(512) NULL,
  "active" bit NOT NULL DEFAULT FALSE,
  "rule_snapshot_json" longtext NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_activity_config_version" ON "club_points_activity_point_config_version" ("activity_id", "version_no");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_config_active" ON "club_points_activity_point_config_version" ("activity_id", "active");

CREATE TABLE IF NOT EXISTS "club_points_activity_registration" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "activity_id" bigint NOT NULL,
  "club_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "status" tinyint NOT NULL,
  "register_time" datetime NOT NULL,
  "cancel_time" datetime NULL,
  "cancel_reason_type" tinyint NULL,
  "cancel_reason" varchar(512) NULL,
  "cancel_operator_user_id" bigint NULL,
  "no_absence_deduct" bit NOT NULL DEFAULT FALSE,
  "special_absence_flag" bit NOT NULL DEFAULT FALSE,
  "special_absence_reason" varchar(512) NULL,
  "special_absence_time" datetime NULL,
  "special_absence_operator_id" bigint NULL,
  "user_name_snapshot" varchar(128) NOT NULL,
  "dept_id_snapshot" bigint NULL,
  "dept_name_snapshot" varchar(128) NULL,
  "mobile_snapshot" varchar(64) NULL,
  "club_name_snapshot" varchar(128) NOT NULL,
  "activity_title_snapshot" varchar(256) NOT NULL,
  "activity_start_time_snapshot" datetime NOT NULL,
  "activity_end_time_snapshot" datetime NOT NULL,
  "active_unique_key" varchar(160) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_activity_registration_active" ON "club_points_activity_registration" ("active_unique_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_registration_activity_status" ON "club_points_activity_registration" ("activity_id", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_registration_user_status" ON "club_points_activity_registration" ("user_id", "status", "register_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_registration_club_user" ON "club_points_activity_registration" ("club_id", "user_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_attendance_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "registration_id" bigint NOT NULL,
  "activity_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "target_type" tinyint NOT NULL,
  "record_time" datetime NOT NULL,
  "source_type" tinyint NOT NULL,
  "operator_user_id" bigint NOT NULL,
  "reason" varchar(512) NULL,
  "client_ip" varchar(64) NULL,
  "remark" varchar(512) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_attendance_registration_target" ON "club_points_attendance_record" ("registration_id", "target_type");
CREATE INDEX IF NOT EXISTS "idx_club_points_attendance_activity_target" ON "club_points_attendance_record" ("activity_id", "target_type");
CREATE INDEX IF NOT EXISTS "idx_club_points_attendance_user_time" ON "club_points_attendance_record" ("user_id", "record_time");

CREATE TABLE IF NOT EXISTS "club_points_attendance_correction" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "attendance_record_id" bigint NULL,
  "registration_id" bigint NOT NULL,
  "activity_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "target_type" tinyint NOT NULL,
  "correction_type" tinyint NOT NULL,
  "before_record_time" datetime NULL,
  "after_record_time" datetime NOT NULL,
  "reason" varchar(512) NOT NULL,
  "operator_user_id" bigint NOT NULL,
  "audit_log_id" bigint NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_attendance_correction_registration" ON "club_points_attendance_correction" ("registration_id", "create_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_attendance_correction_activity" ON "club_points_attendance_correction" ("activity_id", "create_time");

CREATE TABLE IF NOT EXISTS "club_points_activity_settlement_run" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "activity_id" bigint NOT NULL,
  "job_run_id" bigint NULL,
  "run_key" varchar(160) NOT NULL,
  "status" tinyint NOT NULL,
  "settlement_time" datetime NOT NULL,
  "config_version_id" bigint NOT NULL,
  "registration_count" int NOT NULL,
  "success_count" int NOT NULL,
  "skip_count" int NOT NULL,
  "failed_count" int NOT NULL,
  "error_message" varchar(2048) NULL,
  "trigger_source" tinyint NOT NULL,
  "operator_user_id" bigint NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_activity_settlement_run_key" ON "club_points_activity_settlement_run" ("run_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_activity_settlement_activity_status" ON "club_points_activity_settlement_run" ("activity_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_transaction" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "transaction_no" varchar(64) NOT NULL,
  "user_id" bigint NOT NULL,
  "user_name_snapshot" varchar(128) NOT NULL,
  "dept_id_snapshot" bigint NULL,
  "dept_name_snapshot" varchar(128) NULL,
  "direction" tinyint NOT NULL,
  "points" int NOT NULL,
  "point_category" tinyint NOT NULL,
  "point_type_code" varchar(128) NULL,
  "status" tinyint NOT NULL,
  "source_type" tinyint NOT NULL,
  "source_id" bigint NULL,
  "source_item_id" bigint NULL,
  "source_title_snapshot" varchar(256) NULL,
  "issuing_club_id" bigint NULL,
  "issuing_club_code_snapshot" varchar(64) NULL,
  "issuing_club_name_snapshot" varchar(128) NULL,
  "activity_id" bigint NULL,
  "activity_title_snapshot" varchar(256) NULL,
  "activity_date_snapshot" date NULL,
  "rule_version_id" bigint NOT NULL,
  "rule_item_id" bigint NULL,
  "rule_item_code_snapshot" varchar(128) NULL,
  "rule_snapshot_json" longtext NULL,
  "evidence_type" tinyint NULL,
  "material_summary" varchar(1024) NULL,
  "reason" varchar(1024) NULL,
  "occurred_at" datetime NOT NULL,
  "business_year" int NOT NULL,
  "business_month" int NOT NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "reverse_of_transaction_id" bigint NULL,
  "operator_user_id" bigint NULL,
  "audit_log_id" bigint NULL,
  "snapshot_json" longtext NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_transaction_no" ON "club_points_transaction" ("transaction_no");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_transaction_idempotency" ON "club_points_transaction" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_transaction_reverse" ON "club_points_transaction" ("reverse_of_transaction_id");
CREATE INDEX IF NOT EXISTS "idx_club_points_transaction_user_time" ON "club_points_transaction" ("user_id", "occurred_at");
CREATE INDEX IF NOT EXISTS "idx_club_points_transaction_user_year_category" ON "club_points_transaction" ("user_id", "business_year", "point_category");
CREATE INDEX IF NOT EXISTS "idx_club_points_transaction_club_year" ON "club_points_transaction" ("issuing_club_id", "business_year", "direction", "point_category");
CREATE INDEX IF NOT EXISTS "idx_club_points_transaction_source" ON "club_points_transaction" ("source_type", "source_id", "source_item_id");
CREATE INDEX IF NOT EXISTS "idx_club_points_transaction_period" ON "club_points_transaction" ("business_year", "business_month");

CREATE TABLE IF NOT EXISTS "club_points_point_account" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "total_positive_points" int NOT NULL,
  "total_negative_points" int NOT NULL,
  "net_points" int NOT NULL,
  "frozen_points" int NOT NULL,
  "available_points" int NOT NULL,
  "annual_earned_points" int NOT NULL,
  "last_transaction_id" bigint NULL,
  "last_transaction_time" datetime NULL,
  "last_rebuild_time" datetime NULL,
  "version" int NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_point_account_user" ON "club_points_point_account" ("user_id");
CREATE INDEX IF NOT EXISTS "idx_club_points_point_account_available" ON "club_points_point_account" ("available_points");

CREATE TABLE IF NOT EXISTS "club_points_freeze" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "freeze_no" varchar(64) NOT NULL,
  "user_id" bigint NOT NULL,
  "points" int NOT NULL,
  "status" tinyint NOT NULL,
  "source_type" tinyint NOT NULL,
  "source_id" bigint NOT NULL,
  "frozen_at" datetime NOT NULL,
  "converted_at" datetime NULL,
  "released_at" datetime NULL,
  "release_reason" varchar(512) NULL,
  "converted_transaction_id" bigint NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_freeze_no" ON "club_points_freeze" ("freeze_no");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_freeze_idempotency" ON "club_points_freeze" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_freeze_source" ON "club_points_freeze" ("source_type", "source_id");
CREATE INDEX IF NOT EXISTS "idx_club_points_freeze_user_status" ON "club_points_freeze" ("user_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_user_year_status" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "year" int NOT NULL,
  "honor_eligible" bit NOT NULL DEFAULT TRUE,
  "honor_cancel_reason" varchar(512) NULL,
  "honor_cancel_transaction_id" bigint NULL,
  "honor_cancel_time" datetime NULL,
  "annual_positive_points" int NOT NULL,
  "annual_negative_points" int NOT NULL,
  "remark" varchar(512) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_user_year_status_user_year" ON "club_points_user_year_status" ("user_id", "year");
CREATE INDEX IF NOT EXISTS "idx_club_points_user_year_status_year_eligible" ON "club_points_user_year_status" ("year", "honor_eligible");

CREATE TABLE IF NOT EXISTS "club_points_contribution_material" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "club_id" bigint NULL,
  "club_name_snapshot" varchar(128) NULL,
  "type" tinyint NOT NULL,
  "title" varchar(256) NOT NULL,
  "description" text NULL,
  "status" tinyint NOT NULL,
  "rule_version_id" bigint NOT NULL,
  "submitter_user_id" bigint NOT NULL,
  "submit_time" datetime NULL,
  "reviewer_user_id" bigint NULL,
  "review_time" datetime NULL,
  "review_reason" varchar(512) NULL,
  "locked" bit NOT NULL DEFAULT FALSE,
  "direct_created" bit NOT NULL DEFAULT FALSE,
  "request_no" varchar(64) NULL,
  "snapshot_json" longtext NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_contribution_material_request" ON "club_points_contribution_material" ("request_no");
CREATE INDEX IF NOT EXISTS "idx_club_points_contribution_material_club_status" ON "club_points_contribution_material" ("club_id", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_contribution_material_status_submit" ON "club_points_contribution_material" ("status", "submit_time");

CREATE TABLE IF NOT EXISTS "club_points_contribution_item" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "material_id" bigint NOT NULL,
  "club_id" bigint NULL,
  "user_id" bigint NOT NULL,
  "user_name_snapshot" varchar(128) NOT NULL,
  "dept_name_snapshot" varchar(128) NULL,
  "point_category" tinyint NOT NULL,
  "rule_item_id" bigint NULL,
  "rule_item_code" varchar(128) NULL,
  "direction" tinyint NOT NULL,
  "points" int NOT NULL,
  "reason" varchar(1024) NOT NULL,
  "material_summary" varchar(1024) NULL,
  "duty_month" int NULL,
  "recommended_user_id" bigint NULL,
  "award_level" tinyint NULL,
  "approval_result_snapshot" varchar(1024) NULL,
  "transaction_id" bigint NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "effective_unique_key" varchar(192) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_contribution_item_idempotency" ON "club_points_contribution_item" ("idempotency_key");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_contribution_item_effective" ON "club_points_contribution_item" ("effective_unique_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_contribution_item_material" ON "club_points_contribution_item" ("material_id");
CREATE INDEX IF NOT EXISTS "idx_club_points_contribution_item_user_category" ON "club_points_contribution_item" ("user_id", "point_category");

CREATE TABLE IF NOT EXISTS "club_points_contribution_review_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "material_id" bigint NOT NULL,
  "reviewer_user_id" bigint NOT NULL,
  "result" tinyint NOT NULL,
  "reason" varchar(512) NULL,
  "review_time" datetime NOT NULL,
  "material_snapshot_json" longtext NOT NULL,
  "created_transaction_count" int NOT NULL,
  "audit_log_id" bigint NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_contribution_review_material_time" ON "club_points_contribution_review_record" ("material_id", "review_time");

CREATE TABLE IF NOT EXISTS "club_points_redemption_batch" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "year" int NOT NULL,
  "name" varchar(128) NOT NULL,
  "status" tinyint NOT NULL,
  "open_time" datetime NOT NULL,
  "close_time" datetime NOT NULL,
  "description" varchar(2048) NULL,
  "min_available_points" int NOT NULL,
  "qualified_count" int NOT NULL,
  "include_tie_at_cutoff" bit NOT NULL DEFAULT TRUE,
  "qualification_rule_json" longtext NOT NULL,
  "snapshot_generated" bit NOT NULL DEFAULT FALSE,
  "snapshot_generated_time" datetime NULL,
  "rule_version_id" bigint NOT NULL,
  "rule_snapshot_json" longtext NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_batch_year_status" ON "club_points_redemption_batch" ("year", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_batch_open_close" ON "club_points_redemption_batch" ("open_time", "close_time", "status");

CREATE TABLE IF NOT EXISTS "club_points_redemption_gift" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "batch_id" bigint NOT NULL,
  "name" varchar(128) NOT NULL,
  "description" varchar(2048) NULL,
  "points_cost" int NOT NULL,
  "tier_min_points" int NULL,
  "tier_max_points" int NULL,
  "reference_amount_cent" bigint NULL,
  "stock_total" int NOT NULL,
  "stock_locked" int NOT NULL,
  "stock_used" int NOT NULL,
  "status" tinyint NOT NULL,
  "image_file_id" bigint NULL,
  "sort" int NOT NULL,
  "gift_snapshot_json" longtext NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_gift_batch_status" ON "club_points_redemption_gift" ("batch_id", "status", "sort");

CREATE TABLE IF NOT EXISTS "club_points_redemption_eligibility_snapshot" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "batch_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "user_name_snapshot" varchar(128) NOT NULL,
  "dept_name_snapshot" varchar(128) NULL,
  "net_points_snapshot" int NOT NULL,
  "frozen_points_snapshot" int NOT NULL,
  "available_points_snapshot" int NOT NULL,
  "annual_earned_points_snapshot" int NOT NULL,
  "rank_no" int NULL,
  "qualified" bit NOT NULL DEFAULT FALSE,
  "qualification_reason" varchar(512) NULL,
  "tie_at_cutoff" bit NOT NULL DEFAULT FALSE,
  "generated_time" datetime NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_redemption_eligibility_user" ON "club_points_redemption_eligibility_snapshot" ("batch_id", "user_id");
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_eligibility_rank" ON "club_points_redemption_eligibility_snapshot" ("batch_id", "qualified", "rank_no");
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_eligibility_user_batch" ON "club_points_redemption_eligibility_snapshot" ("user_id", "batch_id");

CREATE TABLE IF NOT EXISTS "club_points_redemption_application" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "application_no" varchar(64) NOT NULL,
  "request_no" varchar(64) NOT NULL,
  "batch_id" bigint NOT NULL,
  "gift_id" bigint NOT NULL,
  "eligibility_snapshot_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "status" tinyint NOT NULL,
  "points_cost" int NOT NULL,
  "quantity" int NOT NULL,
  "freeze_id" bigint NULL,
  "stock_lock_id" bigint NULL,
  "deduct_transaction_id" bigint NULL,
  "qualification_rank_snapshot" int NULL,
  "before_net_points" int NOT NULL,
  "before_frozen_points" int NOT NULL,
  "before_available_points" int NOT NULL,
  "after_net_points" int NULL,
  "after_frozen_points" int NULL,
  "after_available_points" int NULL,
  "batch_snapshot_json" longtext NOT NULL,
  "gift_snapshot_json" longtext NOT NULL,
  "apply_time" datetime NOT NULL,
  "cancel_time" datetime NULL,
  "cancel_reason" varchar(512) NULL,
  "reviewer_user_id" bigint NULL,
  "review_time" datetime NULL,
  "review_reason" varchar(512) NULL,
  "direct_issue_time" datetime NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_redemption_application_no" ON "club_points_redemption_application" ("application_no");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_redemption_application_idempotency" ON "club_points_redemption_application" ("idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_application_user_status" ON "club_points_redemption_application" ("user_id", "status", "apply_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_application_batch_status" ON "club_points_redemption_application" ("batch_id", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_application_gift_status" ON "club_points_redemption_application" ("gift_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_stock_lock" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "gift_id" bigint NOT NULL,
  "application_id" bigint NOT NULL,
  "user_id" bigint NOT NULL,
  "quantity" int NOT NULL,
  "status" tinyint NOT NULL,
  "locked_time" datetime NOT NULL,
  "used_time" datetime NULL,
  "released_time" datetime NULL,
  "release_reason" varchar(512) NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_stock_lock_application" ON "club_points_stock_lock" ("application_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_stock_lock_idempotency" ON "club_points_stock_lock" ("idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_stock_lock_gift_status" ON "club_points_stock_lock" ("gift_id", "status");

CREATE TABLE IF NOT EXISTS "club_points_redemption_review_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "application_id" bigint NOT NULL,
  "reviewer_user_id" bigint NOT NULL,
  "result" tinyint NOT NULL,
  "reason" varchar(512) NULL,
  "review_time" datetime NOT NULL,
  "application_snapshot_json" longtext NOT NULL,
  "freeze_snapshot_json" longtext NOT NULL,
  "stock_snapshot_json" longtext NOT NULL,
  "audit_log_id" bigint NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_redemption_review_application_time" ON "club_points_redemption_review_record" ("application_id", "review_time");

CREATE TABLE IF NOT EXISTS "club_points_dispute" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "title" varchar(256) NOT NULL,
  "content" text NOT NULL,
  "target_type" tinyint NOT NULL,
  "target_id" bigint NULL,
  "status" tinyint NOT NULL,
  "submit_time" datetime NOT NULL,
  "handler_user_id" bigint NULL,
  "handle_time" datetime NULL,
  "reply_content" text NULL,
  "related_action_type" tinyint NULL,
  "related_transaction_id" bigint NULL,
  "close_time" datetime NULL,
  "audit_log_id" bigint NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_dispute_user_status_submit" ON "club_points_dispute" ("user_id", "status", "submit_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_dispute_status_submit" ON "club_points_dispute" ("status", "submit_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_dispute_target" ON "club_points_dispute" ("target_type", "target_id");

CREATE TABLE IF NOT EXISTS "club_points_annual_clearing_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "year" int NOT NULL,
  "user_id" bigint NOT NULL,
  "net_points_before" int NOT NULL,
  "frozen_points_before" int NOT NULL,
  "available_points_before" int NOT NULL,
  "clearable_points" int NOT NULL,
  "clear_transaction_id" bigint NULL,
  "status" tinyint NOT NULL,
  "run_id" bigint NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "clear_time" datetime NOT NULL,
  "error_message" varchar(2048) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_annual_clearing_user_year" ON "club_points_annual_clearing_record" ("year", "user_id");
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_annual_clearing_idempotency" ON "club_points_annual_clearing_record" ("idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_annual_clearing_year_status" ON "club_points_annual_clearing_record" ("year", "status");

CREATE TABLE IF NOT EXISTS "club_points_annual_ranking_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "year" int NOT NULL,
  "club_id" bigint NULL,
  "club_code_snapshot" varchar(64) NOT NULL,
  "club_name_snapshot" varchar(128) NOT NULL,
  "activity_points" int NOT NULL,
  "contribution_points" int NOT NULL,
  "reward_points" int NOT NULL,
  "reversed_points" int NOT NULL,
  "total_issued_points" int NOT NULL,
  "rank_no" int NOT NULL,
  "incentive_amount_cent" bigint NOT NULL,
  "confirm_status" tinyint NOT NULL,
  "confirmed_by" bigint NULL,
  "confirmed_time" datetime NULL,
  "budget_record_id" bigint NULL,
  "generated_time" datetime NOT NULL,
  "snapshot_json" longtext NOT NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_annual_ranking_year_club" ON "club_points_annual_ranking_record" ("year", "club_code_snapshot");
CREATE INDEX IF NOT EXISTS "idx_club_points_annual_ranking_year_rank" ON "club_points_annual_ranking_record" ("year", "rank_no");

CREATE TABLE IF NOT EXISTS "club_points_incentive_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "year" int NOT NULL,
  "type" tinyint NOT NULL,
  "club_id" bigint NULL,
  "club_name_snapshot" varchar(128) NULL,
  "user_id" bigint NULL,
  "user_name_snapshot" varchar(128) NULL,
  "title" varchar(256) NOT NULL,
  "amount_cent" bigint NOT NULL,
  "status" tinyint NOT NULL,
  "source_type" tinyint NULL,
  "source_id" bigint NULL,
  "budget_record_id" bigint NULL,
  "confirmed_by" bigint NULL,
  "confirmed_time" datetime NULL,
  "remark" varchar(1024) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_incentive_year_type_status" ON "club_points_incentive_record" ("year", "type", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_incentive_club_year" ON "club_points_incentive_record" ("club_id", "year");
CREATE INDEX IF NOT EXISTS "idx_club_points_incentive_user_year" ON "club_points_incentive_record" ("user_id", "year");

CREATE TABLE IF NOT EXISTS "club_points_budget_record" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "category" tinyint NOT NULL,
  "budget_amount_cent" bigint NOT NULL,
  "actual_amount_cent" bigint NULL,
  "occur_date" date NULL,
  "handler_user_id" bigint NULL,
  "source_type" tinyint NULL,
  "source_id" bigint NULL,
  "description" varchar(2048) NULL,
  "remark" varchar(1024) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_budget_category_date" ON "club_points_budget_record" ("category", "occur_date");
CREATE INDEX IF NOT EXISTS "idx_club_points_budget_source" ON "club_points_budget_record" ("source_type", "source_id");

CREATE TABLE IF NOT EXISTS "club_points_attachment_ref" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NOT NULL,
  "biz_item_id" bigint NULL,
  "attachment_type" tinyint NOT NULL,
  "file_id" bigint NULL,
  "url" varchar(1024) NULL,
  "name" varchar(256) NOT NULL,
  "remark" varchar(512) NULL,
  "status" tinyint NOT NULL,
  "locked" bit NOT NULL DEFAULT FALSE,
  "lock_time" datetime NULL,
  "uploaded_by" bigint NOT NULL,
  "uploaded_time" datetime NOT NULL,
  "admin_append" bit NOT NULL DEFAULT FALSE,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_attachment_ref_biz" ON "club_points_attachment_ref" ("biz_type", "biz_id", "status");
CREATE INDEX IF NOT EXISTS "idx_club_points_attachment_ref_file" ON "club_points_attachment_ref" ("file_id");

CREATE TABLE IF NOT EXISTS "club_points_audit_log" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "action_type" varchar(128) NOT NULL,
  "biz_type" varchar(64) NOT NULL,
  "biz_id" bigint NULL,
  "operator_user_id" bigint NOT NULL,
  "operator_name_snapshot" varchar(128) NOT NULL,
  "operator_role_snapshot" varchar(256) NULL,
  "operation_time" datetime NOT NULL,
  "client_ip" varchar(64) NULL,
  "user_agent" varchar(512) NULL,
  "reason" varchar(1024) NULL,
  "before_json" longtext NULL,
  "after_json" longtext NULL,
  "target_snapshot_json" longtext NULL,
  "success" bit NOT NULL,
  "error_message" varchar(2048) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE INDEX IF NOT EXISTS "idx_club_points_audit_log_biz_time" ON "club_points_audit_log" ("biz_type", "biz_id", "operation_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_audit_log_operator_time" ON "club_points_audit_log" ("operator_user_id", "operation_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_audit_log_action_time" ON "club_points_audit_log" ("action_type", "operation_time");

CREATE TABLE IF NOT EXISTS "club_points_job_run" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "task_type" varchar(128) NOT NULL,
  "biz_type" varchar(64) NULL,
  "biz_id" bigint NULL,
  "run_key" varchar(192) NOT NULL,
  "idempotency_key" varchar(192) NOT NULL,
  "status" tinyint NOT NULL,
  "planned_time" datetime NULL,
  "start_time" datetime NULL,
  "end_time" datetime NULL,
  "trigger_source" tinyint NOT NULL,
  "handler_user_id" bigint NULL,
  "total_count" int NOT NULL DEFAULT 0,
  "success_count" int NOT NULL DEFAULT 0,
  "skip_count" int NOT NULL DEFAULT 0,
  "failed_count" int NOT NULL DEFAULT 0,
  "retry_count" int NOT NULL DEFAULT 0,
  "next_retry_time" datetime NULL,
  "error_type" varchar(128) NULL,
  "error_message" varchar(2048) NULL,
  "result_json" longtext NULL,
  "manual_handle_reason" varchar(1024) NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);
CREATE UNIQUE INDEX IF NOT EXISTS "uk_club_points_job_run_idempotency" ON "club_points_job_run" ("idempotency_key");
CREATE INDEX IF NOT EXISTS "idx_club_points_job_run_task_status_planned" ON "club_points_job_run" ("task_type", "status", "planned_time");
CREATE INDEX IF NOT EXISTS "idx_club_points_job_run_biz" ON "club_points_job_run" ("biz_type", "biz_id");

CREATE TABLE IF NOT EXISTS "system_notify_message" (
  "id" bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY,
  "user_id" bigint NOT NULL,
  "user_type" tinyint NOT NULL,
  "template_id" bigint NOT NULL,
  "template_code" varchar(64) NOT NULL,
  "template_nickname" varchar(64) NOT NULL,
  "template_content" varchar(1024) NOT NULL,
  "template_type" tinyint NOT NULL,
  "template_params" varchar(2048),
  "read_status" bit NOT NULL,
  "read_time" datetime NULL,
  "creator" varchar(64) DEFAULT '',
  "create_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updater" varchar(64) DEFAULT '',
  "update_time" datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  "deleted" bit NOT NULL DEFAULT FALSE,
  PRIMARY KEY ("id")
);

