package cn.iocoder.yudao.module.clubpoints.enums;

/**
 * 俱乐部积分强审计动作类型
 */
public interface ClubAuditActionTypeConstants {

    String REPORT_EXPORT = "REPORT_EXPORT";
    String PHYSICAL_DELETE = "PHYSICAL_DELETE";
    String REVIEW_APPROVE = "REVIEW_APPROVE";
    String POINT_ADJUST = "POINT_ADJUST";
    String POINT_REVERSE = "POINT_REVERSE";
    String ANNUAL_CLEARING_MANUAL = "ANNUAL_CLEARING_MANUAL";
    String CLUB_UPDATE = "CLUB_UPDATE";
    String CLUB_DISABLE = "CLUB_DISABLE";
    String CLUB_ENABLE = "CLUB_ENABLE";
    String CLUB_MEMBER_JOIN = "CLUB_MEMBER_JOIN";
    String CLUB_MEMBER_ADD = "CLUB_MEMBER_ADD";
    String CLUB_MEMBER_EXIT = "CLUB_MEMBER_EXIT";
    String CLUB_MEMBER_REMOVE = "CLUB_MEMBER_REMOVE";
    String CLUB_LEADER_ASSIGN = "CLUB_LEADER_ASSIGN";
    String CLUB_LEADER_REMOVE = "CLUB_LEADER_REMOVE";
    String RULE_PUBLISH = "RULE_PUBLISH";
    String RULE_WITHDRAW = "RULE_WITHDRAW";
    String RULE_DISABLE = "RULE_DISABLE";
    String ACTIVITY_KEY_FIELD_UPDATE = "ACTIVITY_KEY_FIELD_UPDATE";
    String ACTIVITY_CANCEL = "ACTIVITY_CANCEL";
    String ACTIVITY_SETTLEMENT_MANUAL = "ACTIVITY_SETTLEMENT_MANUAL";
    String ATTENDANCE_SUPPLEMENT = "ATTENDANCE_SUPPLEMENT";
    String ATTENDANCE_CORRECT = "ATTENDANCE_CORRECT";
    String SPECIAL_ABSENCE_MARK = "SPECIAL_ABSENCE_MARK";
    String CONTRIBUTION_REVIEW = "CONTRIBUTION_REVIEW";
    String CONTRIBUTION_DIRECT_CREATE = "CONTRIBUTION_DIRECT_CREATE";
    String CONTRIBUTION_VIOLATION_DEDUCT = "CONTRIBUTION_VIOLATION_DEDUCT";
    String CONTRIBUTION_FRAUD_HANDLE = "CONTRIBUTION_FRAUD_HANDLE";

}
