-- 俱乐部员工积分系统 - 正式 MySQL Schema
-- Source of truth: docs/club-points-database-design.md

SET NAMES utf8mb4;

-- ----------------------------
-- 规则
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_rule_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `version_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '版本号',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '规则名称',
  `status` tinyint NOT NULL COMMENT '状态：1 草稿，2 已发布，3 已撤回，4 已停用',
  `publicity_time` datetime NULL COMMENT '公示时间',
  `effective_time` datetime NOT NULL COMMENT '生效时间',
  `published_time` datetime NULL COMMENT '发布时间',
  `disabled_time` datetime NULL COMMENT '停用时间',
  `summary` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '规则摘要',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '规则正文',
  `attachment_snapshot_json` json NULL COMMENT '发布时附件快照',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_rule_version_no` (`version_no`) USING BTREE,
  KEY `idx_club_points_rule_version_status_effective` (`status`, `effective_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '积分制度版本';

CREATE TABLE IF NOT EXISTS `club_points_rule_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `rule_version_id` bigint NOT NULL COMMENT '所属规则版本',
  `item_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '稳定编码',
  `item_name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '中文名称',
  `item_type` tinyint NOT NULL COMMENT '规则项类型：1 分值，2 阈值，3 开关，4 金额，5 文本，6 JSON',
  `category` tinyint NOT NULL COMMENT '规则域',
  `min_points` int NULL COMMENT '分值下限',
  `max_points` int NULL COMMENT '分值上限',
  `default_points` int NULL COMMENT '默认分值',
  `int_value` int NULL COMMENT '整数参数',
  `decimal_value` decimal(18,6) NULL COMMENT '小数参数',
  `text_value` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '文本参数',
  `json_value` json NULL COMMENT '复杂参数',
  `status` tinyint NOT NULL COMMENT '状态：1 启用，2 停用',
  `sort` int NOT NULL COMMENT '排序',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '说明',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_rule_item_version_code` (`rule_version_id`, `item_code`) USING BTREE,
  KEY `idx_club_points_rule_item_code_status` (`item_code`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '积分规则项';

CREATE TABLE IF NOT EXISTS `club_points_rule_publish_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `rule_version_id` bigint NOT NULL COMMENT '规则版本',
  `action` tinyint NOT NULL COMMENT '动作：1 发布，2 撤回，3 停用，4 替代',
  `operator_user_id` bigint NOT NULL COMMENT '操作人',
  `operation_time` datetime NOT NULL COMMENT '操作时间',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原因',
  `before_json` json NULL COMMENT '变更前快照',
  `after_json` json NULL COMMENT '变更后快照',
  `audit_log_id` bigint NULL COMMENT '强审计 ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_rule_publish_version_time` (`rule_version_id`, `operation_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '积分规则发布记录';

-- ----------------------------
-- 俱乐部
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_club` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `code` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部编号',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部名称',
  `status` tinyint NOT NULL COMMENT '状态：1 启用，2 停用',
  `description` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '介绍',
  `contact_text` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '联系方式展示文本',
  `cover_file_id` bigint NULL COMMENT '封面文件 ID',
  `sort` int NOT NULL COMMENT '排序',
  `disabled_time` datetime NULL COMMENT '停用时间',
  `disabled_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '停用原因',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_club_code` (`code`) USING BTREE,
  UNIQUE KEY `uk_club_points_club_name` (`name`) USING BTREE,
  KEY `idx_club_points_club_status_sort` (`status`, `sort`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '俱乐部';

CREATE TABLE IF NOT EXISTS `club_points_club_member` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `club_id` bigint NOT NULL COMMENT '俱乐部 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `dept_id_snapshot` bigint NULL COMMENT '加入时部门 ID 快照',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '员工姓名快照',
  `dept_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '部门名称快照',
  `mobile_snapshot` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '联系方式快照',
  `club_code_snapshot` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部编号快照',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部名称快照',
  `status` tinyint NOT NULL COMMENT '状态：1 有效，2 自主退出，3 管理员移除',
  `join_time` datetime NOT NULL COMMENT '加入时间',
  `leave_time` datetime NULL COMMENT '退出或移除时间',
  `leave_reason_type` tinyint NULL COMMENT '退出或移除原因类型',
  `leave_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '退出或移除原因',
  `operator_user_id` bigint NULL COMMENT '移除操作人',
  `active_unique_key` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '有效关系唯一键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_club_member_active` (`active_unique_key`) USING BTREE,
  KEY `idx_club_points_club_member_club_status` (`club_id`, `status`) USING BTREE,
  KEY `idx_club_points_club_member_user_status` (`user_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '俱乐部成员关系';

CREATE TABLE IF NOT EXISTS `club_points_club_leader` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `club_id` bigint NOT NULL COMMENT '俱乐部 ID',
  `user_id` bigint NOT NULL COMMENT '负责人用户 ID',
  `status` tinyint NOT NULL COMMENT '状态：1 有效，2 解除',
  `assigned_time` datetime NOT NULL COMMENT '任命时间',
  `removed_time` datetime NULL COMMENT '解除时间',
  `assigned_by` bigint NOT NULL COMMENT '任命操作人',
  `removed_by` bigint NULL COMMENT '解除操作人',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任免原因',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部名称快照',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '负责人姓名快照',
  `active_unique_key` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '有效关系唯一键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_club_leader_active` (`active_unique_key`) USING BTREE,
  KEY `idx_club_points_club_leader_club_status` (`club_id`, `status`) USING BTREE,
  KEY `idx_club_points_club_leader_user_status` (`user_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '俱乐部负责人关系';

-- ----------------------------
-- 活动
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_activity` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `club_id` bigint NOT NULL COMMENT '所属俱乐部',
  `club_code_snapshot` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部编号快照',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部名称快照',
  `title` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动标题',
  `location` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '活动地点',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '活动说明',
  `cover_file_id` bigint NULL COMMENT '封面文件',
  `level` tinyint NOT NULL COMMENT '活动等级：1 小型，2 中型，3 大型',
  `status` tinyint NOT NULL COMMENT '活动状态',
  `start_time` datetime NOT NULL COMMENT '开始时间',
  `end_time` datetime NOT NULL COMMENT '结束时间',
  `registration_deadline` datetime NOT NULL COMMENT '报名截止时间',
  `cancel_deadline_time` datetime NULL COMMENT '自助取消截止时间',
  `checkin_start_time` datetime NOT NULL COMMENT '签到窗口开始',
  `checkin_end_time` datetime NOT NULL COMMENT '签到窗口结束',
  `checkout_mode` tinyint NOT NULL COMMENT '签退模式：1 按结束时间，2 按开始后时长',
  `checkout_start_time` datetime NOT NULL COMMENT '签退窗口开始',
  `checkout_end_time` datetime NOT NULL COMMENT '签退窗口结束',
  `current_config_version_id` bigint NULL COMMENT '当前活动积分配置版本',
  `creator_user_id` bigint NOT NULL COMMENT '创建人',
  `submit_time` datetime NULL COMMENT '提交审核时间',
  `publish_time` datetime NULL COMMENT '发布时间',
  `cancel_time` datetime NULL COMMENT '取消时间',
  `cancel_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '取消原因',
  `snapshot_json` json NULL COMMENT '删除前活动快照',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_activity_club_status_start` (`club_id`, `status`, `start_time`) USING BTREE,
  KEY `idx_club_points_activity_status_start` (`status`, `start_time`) USING BTREE,
  KEY `idx_club_points_activity_end_status` (`end_time`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '活动';

CREATE TABLE IF NOT EXISTS `club_points_activity_review_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `activity_id` bigint NOT NULL COMMENT '活动 ID',
  `reviewer_user_id` bigint NOT NULL COMMENT '审核人',
  `result` tinyint NOT NULL COMMENT '结果：1 通过，2 驳回',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '审核意见',
  `review_time` datetime NOT NULL COMMENT '审核时间',
  `activity_snapshot_json` json NOT NULL COMMENT '审核时活动快照',
  `audit_log_id` bigint NULL COMMENT '强审计 ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_activity_review_activity_time` (`activity_id`, `review_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '活动审核记录';

CREATE TABLE IF NOT EXISTS `club_points_activity_point_config_version` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `activity_id` bigint NOT NULL COMMENT '活动 ID',
  `version_no` int NOT NULL COMMENT '版本号',
  `level` tinyint NOT NULL COMMENT '活动等级快照',
  `base_points` int NOT NULL COMMENT '基础参与积分',
  `full_extra_points` int NOT NULL COMMENT '全程额外积分',
  `rule_version_id` bigint NOT NULL COMMENT '规则版本',
  `base_rule_item_id` bigint NULL COMMENT '基础积分规则项',
  `full_rule_item_id` bigint NULL COMMENT '全程额外规则项',
  `effective_time` datetime NOT NULL COMMENT '配置生效时间',
  `created_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '创建原因',
  `active` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否当前有效',
  `rule_snapshot_json` json NOT NULL COMMENT '规则快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_activity_config_version` (`activity_id`, `version_no`) USING BTREE,
  KEY `idx_club_points_activity_config_active` (`activity_id`, `active`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '活动积分配置版本';

CREATE TABLE IF NOT EXISTS `club_points_activity_registration` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `activity_id` bigint NOT NULL COMMENT '活动 ID',
  `club_id` bigint NOT NULL COMMENT '冗余俱乐部 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `status` tinyint NOT NULL COMMENT '状态：1 已报名，2 已取消',
  `register_time` datetime NOT NULL COMMENT '报名时间',
  `cancel_time` datetime NULL COMMENT '取消时间',
  `cancel_reason_type` tinyint NULL COMMENT '取消原因类型',
  `cancel_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '取消说明',
  `cancel_operator_user_id` bigint NULL COMMENT '取消操作人',
  `no_absence_deduct` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否不计缺席扣分',
  `special_absence_flag` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否特殊请假缺席',
  `special_absence_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '特殊缺席原因',
  `special_absence_time` datetime NULL COMMENT '特殊缺席标记时间',
  `special_absence_operator_id` bigint NULL COMMENT '特殊缺席标记人',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '员工姓名快照',
  `dept_id_snapshot` bigint NULL COMMENT '部门 ID 快照',
  `dept_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '部门名称快照',
  `mobile_snapshot` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '联系方式快照',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部名称快照',
  `activity_title_snapshot` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '活动标题快照',
  `activity_start_time_snapshot` datetime NOT NULL COMMENT '活动开始时间快照',
  `activity_end_time_snapshot` datetime NOT NULL COMMENT '活动结束时间快照',
  `active_unique_key` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '有效报名唯一键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_activity_registration_active` (`active_unique_key`) USING BTREE,
  KEY `idx_club_points_activity_registration_activity_status` (`activity_id`, `status`) USING BTREE,
  KEY `idx_club_points_activity_registration_user_status` (`user_id`, `status`, `register_time`) USING BTREE,
  KEY `idx_club_points_activity_registration_club_user` (`club_id`, `user_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '活动报名记录';

CREATE TABLE IF NOT EXISTS `club_points_attendance_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `registration_id` bigint NOT NULL COMMENT '报名 ID',
  `activity_id` bigint NOT NULL COMMENT '活动 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `target_type` tinyint NOT NULL COMMENT '目标类型：1 签到，2 签退',
  `record_time` datetime NOT NULL COMMENT '签到或签退时间',
  `source_type` tinyint NOT NULL COMMENT '来源：1 自助，2 补录，3 修正',
  `operator_user_id` bigint NOT NULL COMMENT '操作人',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '补录或修正原因',
  `client_ip` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '操作 IP',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_attendance_registration_target` (`registration_id`, `target_type`) USING BTREE,
  KEY `idx_club_points_attendance_activity_target` (`activity_id`, `target_type`) USING BTREE,
  KEY `idx_club_points_attendance_user_time` (`user_id`, `record_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '签到签退有效事实';

CREATE TABLE IF NOT EXISTS `club_points_attendance_correction` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `attendance_record_id` bigint NULL COMMENT '被修正记录',
  `registration_id` bigint NOT NULL COMMENT '报名 ID',
  `activity_id` bigint NOT NULL COMMENT '活动 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `target_type` tinyint NOT NULL COMMENT '签到或签退',
  `correction_type` tinyint NOT NULL COMMENT '修正类型：1 补录，2 修正',
  `before_record_time` datetime NULL COMMENT '修正前时间',
  `after_record_time` datetime NOT NULL COMMENT '修正后时间',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原因',
  `operator_user_id` bigint NOT NULL COMMENT '操作人',
  `audit_log_id` bigint NOT NULL COMMENT '强审计 ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_attendance_correction_registration` (`registration_id`, `create_time`) USING BTREE,
  KEY `idx_club_points_attendance_correction_activity` (`activity_id`, `create_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '签到签退补录修正记录';

CREATE TABLE IF NOT EXISTS `club_points_activity_settlement_run` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `activity_id` bigint NOT NULL COMMENT '活动 ID',
  `job_run_id` bigint NULL COMMENT '通用任务运行记录 ID',
  `run_key` varchar(160) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '结算批次键',
  `status` tinyint NOT NULL COMMENT '任务状态',
  `settlement_time` datetime NOT NULL COMMENT '结算执行时间',
  `config_version_id` bigint NOT NULL COMMENT '使用的活动积分配置版本',
  `registration_count` int NOT NULL COMMENT '报名数',
  `success_count` int NOT NULL COMMENT '成功处理数',
  `skip_count` int NOT NULL COMMENT '跳过数',
  `failed_count` int NOT NULL COMMENT '失败数',
  `error_message` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误摘要',
  `trigger_source` tinyint NOT NULL COMMENT '触发来源：1 定时，2 管理员手动',
  `operator_user_id` bigint NULL COMMENT '手动触发人',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_activity_settlement_run_key` (`run_key`) USING BTREE,
  KEY `idx_club_points_activity_settlement_activity_status` (`activity_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '活动结算运行记录';

-- ----------------------------
-- 账本
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_transaction` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `transaction_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '流水号',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '员工姓名快照',
  `dept_id_snapshot` bigint NULL COMMENT '部门 ID 快照',
  `dept_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '部门名称快照',
  `direction` tinyint NOT NULL COMMENT '方向：1 增加，2 扣减',
  `points` int NOT NULL COMMENT '积分绝对值',
  `point_category` tinyint NOT NULL COMMENT '积分分类',
  `point_type_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '细分类型编码',
  `status` tinyint NOT NULL COMMENT '状态：1 有效，2 已被撤销，3 撤销流水',
  `source_type` tinyint NOT NULL COMMENT '来源类型',
  `source_id` bigint NULL COMMENT '来源主对象 ID',
  `source_item_id` bigint NULL COMMENT '来源明细 ID',
  `source_title_snapshot` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '来源名称快照',
  `issuing_club_id` bigint NULL COMMENT '发放俱乐部 ID',
  `issuing_club_code_snapshot` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '发放俱乐部编号快照',
  `issuing_club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '发放俱乐部名称快照',
  `activity_id` bigint NULL COMMENT '关联活动 ID',
  `activity_title_snapshot` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '活动标题快照',
  `activity_date_snapshot` date NULL COMMENT '活动日期快照',
  `rule_version_id` bigint NOT NULL COMMENT '规则版本',
  `rule_item_id` bigint NULL COMMENT '规则项',
  `rule_item_code_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '规则项编码快照',
  `rule_snapshot_json` json NULL COMMENT '规则快照',
  `evidence_type` tinyint NULL COMMENT '证明材料类型',
  `material_summary` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '材料摘要',
  `reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原因',
  `occurred_at` datetime NOT NULL COMMENT '业务发生时间',
  `business_year` int NOT NULL COMMENT '业务年度',
  `business_month` int NOT NULL COMMENT '业务月份 yyyyMM',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '幂等键',
  `reverse_of_transaction_id` bigint NULL COMMENT '撤销流水指向原流水',
  `operator_user_id` bigint NULL COMMENT '操作人或系统任务操作者',
  `audit_log_id` bigint NULL COMMENT '强审计 ID',
  `snapshot_json` json NULL COMMENT '其他完整来源快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_transaction_no` (`transaction_no`) USING BTREE,
  UNIQUE KEY `uk_club_points_transaction_idempotency` (`idempotency_key`) USING BTREE,
  UNIQUE KEY `uk_club_points_transaction_reverse` (`reverse_of_transaction_id`) USING BTREE,
  KEY `idx_club_points_transaction_user_time` (`user_id`, `occurred_at`) USING BTREE,
  KEY `idx_club_points_transaction_user_year_category` (`user_id`, `business_year`, `point_category`) USING BTREE,
  KEY `idx_club_points_transaction_club_year` (`issuing_club_id`, `business_year`, `direction`, `point_category`) USING BTREE,
  KEY `idx_club_points_transaction_source` (`source_type`, `source_id`, `source_item_id`) USING BTREE,
  KEY `idx_club_points_transaction_period` (`business_year`, `business_month`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '积分流水事实源';

CREATE TABLE IF NOT EXISTS `club_points_point_account` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `total_positive_points` int NOT NULL COMMENT '全历史有效正向积分总和',
  `total_negative_points` int NOT NULL COMMENT '全历史有效负向积分绝对值总和',
  `net_points` int NOT NULL COMMENT '账户净积分',
  `frozen_points` int NOT NULL COMMENT '当前有效冻结积分',
  `available_points` int NOT NULL COMMENT '当前可用积分',
  `annual_earned_points` int NOT NULL COMMENT '当前年度累计获取积分缓存',
  `last_transaction_id` bigint NULL COMMENT '最近流水',
  `last_transaction_time` datetime NULL COMMENT '最近流水时间',
  `last_rebuild_time` datetime NULL COMMENT '最近重算时间',
  `version` int NOT NULL COMMENT '乐观锁版本',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_point_account_user` (`user_id`) USING BTREE,
  KEY `idx_club_points_point_account_available` (`available_points`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '员工积分账户缓存';

CREATE TABLE IF NOT EXISTS `club_points_freeze` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `freeze_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '冻结号',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `points` int NOT NULL COMMENT '冻结积分',
  `status` tinyint NOT NULL COMMENT '状态：1 冻结中，2 已转扣减，3 已释放',
  `source_type` tinyint NOT NULL COMMENT '来源类型',
  `source_id` bigint NOT NULL COMMENT '来源 ID',
  `frozen_at` datetime NOT NULL COMMENT '冻结时间',
  `converted_at` datetime NULL COMMENT '转扣减时间',
  `released_at` datetime NULL COMMENT '释放时间',
  `release_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '释放原因',
  `converted_transaction_id` bigint NULL COMMENT '审核通过生成的兑换扣减流水',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '幂等键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_freeze_no` (`freeze_no`) USING BTREE,
  UNIQUE KEY `uk_club_points_freeze_idempotency` (`idempotency_key`) USING BTREE,
  UNIQUE KEY `uk_club_points_freeze_source` (`source_type`, `source_id`) USING BTREE,
  KEY `idx_club_points_freeze_user_status` (`user_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '积分冻结记录';

CREATE TABLE IF NOT EXISTS `club_points_user_year_status` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `year` int NOT NULL COMMENT '年度',
  `honor_eligible` bit(1) NOT NULL DEFAULT b'1' COMMENT '是否具备年度评优资格',
  `honor_cancel_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '取消原因',
  `honor_cancel_transaction_id` bigint NULL COMMENT '关联扣分或调整流水',
  `honor_cancel_time` datetime NULL COMMENT '取消时间',
  `annual_positive_points` int NOT NULL COMMENT '年度正向获取积分缓存',
  `annual_negative_points` int NOT NULL COMMENT '年度扣减积分缓存',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_user_year_status_user_year` (`user_id`, `year`) USING BTREE,
  KEY `idx_club_points_user_year_status_year_eligible` (`year`, `honor_eligible`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '员工年度状态和评优资格';

-- ----------------------------
-- 非签到
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_contribution_material` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `club_id` bigint NULL COMMENT '发放俱乐部',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '俱乐部名称快照',
  `type` tinyint NOT NULL COMMENT '材料类型',
  `title` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '材料标题',
  `description` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '材料说明',
  `status` tinyint NOT NULL COMMENT '材料状态',
  `rule_version_id` bigint NOT NULL COMMENT '规则版本',
  `submitter_user_id` bigint NOT NULL COMMENT '提交人',
  `submit_time` datetime NULL COMMENT '提交时间',
  `reviewer_user_id` bigint NULL COMMENT '审核人',
  `review_time` datetime NULL COMMENT '审核时间',
  `review_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '审核意见',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '审核通过后锁定',
  `direct_created` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否管理员代录',
  `request_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '管理员代录请求号',
  `snapshot_json` json NULL COMMENT '删除或审核通过时材料快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_contribution_material_request` (`request_no`) USING BTREE,
  KEY `idx_club_points_contribution_material_club_status` (`club_id`, `status`) USING BTREE,
  KEY `idx_club_points_contribution_material_status_submit` (`status`, `submit_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '非签到积分材料';

CREATE TABLE IF NOT EXISTS `club_points_contribution_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `material_id` bigint NOT NULL COMMENT '材料 ID',
  `club_id` bigint NULL COMMENT '发放俱乐部冗余',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '员工姓名快照',
  `dept_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '部门快照',
  `point_category` tinyint NOT NULL COMMENT '积分分类',
  `rule_item_id` bigint NULL COMMENT '规则项',
  `rule_item_code` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '规则项编码快照',
  `direction` tinyint NOT NULL COMMENT '方向：1 增加，2 扣减',
  `points` int NOT NULL COMMENT '实际分值',
  `reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '原因',
  `material_summary` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '材料摘要',
  `duty_month` int NULL COMMENT '月度履职月份 yyyyMM',
  `recommended_user_id` bigint NULL COMMENT '推荐新会员时填写',
  `award_level` tinyint NULL COMMENT '获奖等级',
  `approval_result_snapshot` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '特殊贡献线下审批结果',
  `transaction_id` bigint NULL COMMENT '审核通过后生成的积分流水',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '明细发分幂等键',
  `effective_unique_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '业务唯一键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_contribution_item_idempotency` (`idempotency_key`) USING BTREE,
  UNIQUE KEY `uk_club_points_contribution_item_effective` (`effective_unique_key`) USING BTREE,
  KEY `idx_club_points_contribution_item_material` (`material_id`) USING BTREE,
  KEY `idx_club_points_contribution_item_user_category` (`user_id`, `point_category`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '非签到积分材料明细';

CREATE TABLE IF NOT EXISTS `club_points_contribution_review_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `material_id` bigint NOT NULL COMMENT '材料 ID',
  `reviewer_user_id` bigint NOT NULL COMMENT '审核人',
  `result` tinyint NOT NULL COMMENT '审核结果',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '审核意见',
  `review_time` datetime NOT NULL COMMENT '审核时间',
  `material_snapshot_json` json NOT NULL COMMENT '审核时材料快照',
  `created_transaction_count` int NOT NULL COMMENT '生成流水条数',
  `audit_log_id` bigint NOT NULL COMMENT '强审计 ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_contribution_review_material_time` (`material_id`, `review_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '非签到积分材料审核记录';

-- ----------------------------
-- 兑换
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_redemption_batch` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `year` int NOT NULL COMMENT '批次年度',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '批次名称',
  `status` tinyint NOT NULL COMMENT '批次状态',
  `open_time` datetime NOT NULL COMMENT '开放时间',
  `close_time` datetime NOT NULL COMMENT '关闭时间',
  `description` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '说明',
  `min_available_points` int NOT NULL COMMENT '最低可用积分',
  `qualified_count` int NOT NULL COMMENT '默认资格人数',
  `include_tie_at_cutoff` bit(1) NOT NULL DEFAULT b'1' COMMENT '第 N 名同分是否全进',
  `qualification_rule_json` json NOT NULL COMMENT '资格规则快照',
  `snapshot_generated` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否已生成资格快照',
  `snapshot_generated_time` datetime NULL COMMENT '快照生成时间',
  `rule_version_id` bigint NOT NULL COMMENT '规则版本',
  `rule_snapshot_json` json NOT NULL COMMENT '规则快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_redemption_batch_year_status` (`year`, `status`) USING BTREE,
  KEY `idx_club_points_redemption_batch_open_close` (`open_time`, `close_time`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '兑换批次';

CREATE TABLE IF NOT EXISTS `club_points_redemption_gift` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `batch_id` bigint NOT NULL COMMENT '批次 ID',
  `name` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '礼品名称',
  `description` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '说明',
  `points_cost` int NOT NULL COMMENT '消耗积分',
  `tier_min_points` int NULL COMMENT '制度档位下限',
  `tier_max_points` int NULL COMMENT '制度档位上限',
  `reference_amount_cent` bigint NULL COMMENT '参考价值，单位分',
  `stock_total` int NOT NULL COMMENT '总库存',
  `stock_locked` int NOT NULL COMMENT '已锁定库存',
  `stock_used` int NOT NULL COMMENT '已审核通过使用库存',
  `status` tinyint NOT NULL COMMENT '状态：1 上架，2 下架',
  `image_file_id` bigint NULL COMMENT '图片文件',
  `sort` int NOT NULL COMMENT '排序',
  `gift_snapshot_json` json NULL COMMENT '重要变更快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_redemption_gift_batch_status` (`batch_id`, `status`, `sort`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '兑换礼品';

CREATE TABLE IF NOT EXISTS `club_points_redemption_eligibility_snapshot` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `batch_id` bigint NOT NULL COMMENT '批次 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '员工姓名快照',
  `dept_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '部门快照',
  `net_points_snapshot` int NOT NULL COMMENT '账户净积分快照',
  `frozen_points_snapshot` int NOT NULL COMMENT '冻结积分快照',
  `available_points_snapshot` int NOT NULL COMMENT '可用积分快照',
  `annual_earned_points_snapshot` int NOT NULL COMMENT '年度累计获取积分快照',
  `rank_no` int NULL COMMENT '排名',
  `qualified` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否具备资格',
  `qualification_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '资格说明',
  `tie_at_cutoff` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否因 cutoff 同分进入',
  `generated_time` datetime NOT NULL COMMENT '生成时间',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_redemption_eligibility_user` (`batch_id`, `user_id`) USING BTREE,
  KEY `idx_club_points_redemption_eligibility_rank` (`batch_id`, `qualified`, `rank_no`) USING BTREE,
  KEY `idx_club_points_redemption_eligibility_user_batch` (`user_id`, `batch_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '兑换资格快照';

CREATE TABLE IF NOT EXISTS `club_points_redemption_application` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `application_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '申请号',
  `request_no` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '前端请求号',
  `batch_id` bigint NOT NULL COMMENT '批次 ID',
  `gift_id` bigint NOT NULL COMMENT '礼品 ID',
  `eligibility_snapshot_id` bigint NOT NULL COMMENT '资格快照 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `status` tinyint NOT NULL COMMENT '申请状态',
  `points_cost` int NOT NULL COMMENT '消耗积分',
  `quantity` int NOT NULL COMMENT '数量',
  `freeze_id` bigint NULL COMMENT '冻结记录',
  `stock_lock_id` bigint NULL COMMENT '库存锁',
  `deduct_transaction_id` bigint NULL COMMENT '兑换扣减流水',
  `qualification_rank_snapshot` int NULL COMMENT '资格排名快照',
  `before_net_points` int NOT NULL COMMENT '申请前账户净积分快照',
  `before_frozen_points` int NOT NULL COMMENT '申请前冻结积分快照',
  `before_available_points` int NOT NULL COMMENT '申请前可用积分快照',
  `after_net_points` int NULL COMMENT '审核通过后账户净积分快照',
  `after_frozen_points` int NULL COMMENT '审核通过后冻结积分快照',
  `after_available_points` int NULL COMMENT '审核通过后可用积分快照',
  `batch_snapshot_json` json NOT NULL COMMENT '批次快照',
  `gift_snapshot_json` json NOT NULL COMMENT '礼品快照',
  `apply_time` datetime NOT NULL COMMENT '申请时间',
  `cancel_time` datetime NULL COMMENT '审核前取消时间',
  `cancel_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '取消原因',
  `reviewer_user_id` bigint NULL COMMENT '审核人',
  `review_time` datetime NULL COMMENT '审核时间',
  `review_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '审核意见',
  `direct_issue_time` datetime NULL COMMENT '直接发放时间',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '申请幂等键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_redemption_application_no` (`application_no`) USING BTREE,
  UNIQUE KEY `uk_club_points_redemption_application_idempotency` (`idempotency_key`) USING BTREE,
  KEY `idx_club_points_redemption_application_user_status` (`user_id`, `status`, `apply_time`) USING BTREE,
  KEY `idx_club_points_redemption_application_batch_status` (`batch_id`, `status`) USING BTREE,
  KEY `idx_club_points_redemption_application_gift_status` (`gift_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '兑换申请';

CREATE TABLE IF NOT EXISTS `club_points_stock_lock` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `gift_id` bigint NOT NULL COMMENT '礼品 ID',
  `application_id` bigint NOT NULL COMMENT '兑换申请 ID',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `quantity` int NOT NULL COMMENT '锁定数量',
  `status` tinyint NOT NULL COMMENT '状态：1 锁定中，2 已使用，3 已释放',
  `locked_time` datetime NOT NULL COMMENT '锁定时间',
  `used_time` datetime NULL COMMENT '使用时间',
  `released_time` datetime NULL COMMENT '释放时间',
  `release_reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '释放原因',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '幂等键',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_stock_lock_application` (`application_id`) USING BTREE,
  UNIQUE KEY `uk_club_points_stock_lock_idempotency` (`idempotency_key`) USING BTREE,
  KEY `idx_club_points_stock_lock_gift_status` (`gift_id`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '礼品库存锁定';

CREATE TABLE IF NOT EXISTS `club_points_redemption_review_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `application_id` bigint NOT NULL COMMENT '兑换申请 ID',
  `reviewer_user_id` bigint NOT NULL COMMENT '审核人',
  `result` tinyint NOT NULL COMMENT '结果：1 通过，2 拒绝',
  `reason` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '审核意见',
  `review_time` datetime NOT NULL COMMENT '审核时间',
  `application_snapshot_json` json NOT NULL COMMENT '审核时申请快照',
  `freeze_snapshot_json` json NOT NULL COMMENT '冻结处理快照',
  `stock_snapshot_json` json NOT NULL COMMENT '库存处理快照',
  `audit_log_id` bigint NOT NULL COMMENT '强审计 ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_redemption_review_application_time` (`application_id`, `review_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '兑换审核记录';

-- ----------------------------
-- 年度
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_dispute` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `user_id` bigint NOT NULL COMMENT '提交员工',
  `title` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '标题',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '异议内容',
  `target_type` tinyint NOT NULL COMMENT '目标类型',
  `target_id` bigint NULL COMMENT '目标业务 ID',
  `status` tinyint NOT NULL COMMENT '异议状态',
  `submit_time` datetime NOT NULL COMMENT '提交时间',
  `handler_user_id` bigint NULL COMMENT '处理人',
  `handle_time` datetime NULL COMMENT '处理时间',
  `reply_content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '回复内容',
  `related_action_type` tinyint NULL COMMENT '关联动作类型',
  `related_transaction_id` bigint NULL COMMENT '关联调整或撤销流水',
  `close_time` datetime NULL COMMENT '关闭时间',
  `audit_log_id` bigint NULL COMMENT '强审计 ID',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_dispute_user_status_submit` (`user_id`, `status`, `submit_time`) USING BTREE,
  KEY `idx_club_points_dispute_status_submit` (`status`, `submit_time`) USING BTREE,
  KEY `idx_club_points_dispute_target` (`target_type`, `target_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '员工异议';

CREATE TABLE IF NOT EXISTS `club_points_annual_clearing_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `year` int NOT NULL COMMENT '清零年度',
  `user_id` bigint NOT NULL COMMENT '员工 ID',
  `net_points_before` int NOT NULL COMMENT '清零前净积分',
  `frozen_points_before` int NOT NULL COMMENT '清零前冻结积分',
  `available_points_before` int NOT NULL COMMENT '清零前可用积分',
  `clearable_points` int NOT NULL COMMENT '实际清零积分',
  `clear_transaction_id` bigint NULL COMMENT '清零负向流水',
  `status` tinyint NOT NULL COMMENT '状态',
  `run_id` bigint NULL COMMENT '任务运行 ID',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '幂等键',
  `clear_time` datetime NOT NULL COMMENT '清零时间',
  `error_message` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误说明',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_annual_clearing_user_year` (`year`, `user_id`) USING BTREE,
  UNIQUE KEY `uk_club_points_annual_clearing_idempotency` (`idempotency_key`) USING BTREE,
  KEY `idx_club_points_annual_clearing_year_status` (`year`, `status`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '年度清零记录';

CREATE TABLE IF NOT EXISTS `club_points_annual_ranking_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `year` int NOT NULL COMMENT '年度',
  `club_id` bigint NULL COMMENT '俱乐部 ID',
  `club_code_snapshot` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部编号快照',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '俱乐部名称快照',
  `activity_points` int NOT NULL COMMENT '活动发放积分',
  `contribution_points` int NOT NULL COMMENT '主动贡献发放积分',
  `reward_points` int NOT NULL COMMENT '特殊奖励发放积分',
  `reversed_points` int NOT NULL COMMENT '已撤销积分',
  `total_issued_points` int NOT NULL COMMENT '年度发放积分净额',
  `rank_no` int NOT NULL COMMENT '排名',
  `incentive_amount_cent` bigint NOT NULL COMMENT '激励建议金额',
  `confirm_status` tinyint NOT NULL COMMENT '确认状态',
  `confirmed_by` bigint NULL COMMENT '确认人',
  `confirmed_time` datetime NULL COMMENT '确认时间',
  `budget_record_id` bigint NULL COMMENT '关联经费记录',
  `generated_time` datetime NOT NULL COMMENT '生成时间',
  `snapshot_json` json NOT NULL COMMENT '排名计算快照',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_annual_ranking_year_club` (`year`, `club_code_snapshot`) USING BTREE,
  KEY `idx_club_points_annual_ranking_year_rank` (`year`, `rank_no`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '俱乐部年度排名记录';

CREATE TABLE IF NOT EXISTS `club_points_incentive_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `year` int NOT NULL COMMENT '年度',
  `type` tinyint NOT NULL COMMENT '类型',
  `club_id` bigint NULL COMMENT '俱乐部 ID',
  `club_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '俱乐部名称快照',
  `user_id` bigint NULL COMMENT '个人荣誉员工 ID',
  `user_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '员工姓名快照',
  `title` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '激励名称',
  `amount_cent` bigint NOT NULL COMMENT '金额，单位分',
  `status` tinyint NOT NULL COMMENT '状态',
  `source_type` tinyint NULL COMMENT '来源类型',
  `source_id` bigint NULL COMMENT '来源 ID',
  `budget_record_id` bigint NULL COMMENT '预算经费记录',
  `confirmed_by` bigint NULL COMMENT '确认人',
  `confirmed_time` datetime NULL COMMENT '确认时间',
  `remark` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_incentive_year_type_status` (`year`, `type`, `status`) USING BTREE,
  KEY `idx_club_points_incentive_club_year` (`club_id`, `year`) USING BTREE,
  KEY `idx_club_points_incentive_user_year` (`user_id`, `year`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '运营激励记录';

CREATE TABLE IF NOT EXISTS `club_points_budget_record` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `category` tinyint NOT NULL COMMENT '预算类别',
  `budget_amount_cent` bigint NOT NULL COMMENT '预算金额，单位分',
  `actual_amount_cent` bigint NULL COMMENT '实际支出，单位分',
  `occur_date` date NULL COMMENT '发生日期',
  `handler_user_id` bigint NULL COMMENT '经办人',
  `source_type` tinyint NULL COMMENT '来源类型',
  `source_id` bigint NULL COMMENT '来源 ID',
  `description` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '说明',
  `remark` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_budget_category_date` (`category`, `occur_date`) USING BTREE,
  KEY `idx_club_points_budget_source` (`source_type`, `source_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '预算和经费记录';

-- ----------------------------
-- 支撑
-- ----------------------------

CREATE TABLE IF NOT EXISTS `club_points_attachment_ref` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `biz_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务类型',
  `biz_id` bigint NOT NULL COMMENT '业务 ID',
  `biz_item_id` bigint NULL COMMENT '明细 ID',
  `attachment_type` tinyint NOT NULL COMMENT '附件类型：1 文件，2 外部链接',
  `file_id` bigint NULL COMMENT '文件 ID',
  `url` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '外部链接',
  `name` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '展示名称',
  `remark` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '备注',
  `status` tinyint NOT NULL COMMENT '状态：1 有效，2 已替换，3 已删除',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否锁定',
  `lock_time` datetime NULL COMMENT '锁定时间',
  `uploaded_by` bigint NOT NULL COMMENT '上传人',
  `uploaded_time` datetime NOT NULL COMMENT '上传时间',
  `admin_append` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否管理员审核后追加',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_attachment_ref_biz` (`biz_type`, `biz_id`, `status`) USING BTREE,
  KEY `idx_club_points_attachment_ref_file` (`file_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '业务附件和外部链接绑定';

CREATE TABLE IF NOT EXISTS `club_points_audit_log` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `action_type` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '动作类型',
  `biz_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '业务类型',
  `biz_id` bigint NULL COMMENT '业务 ID',
  `operator_user_id` bigint NOT NULL COMMENT '操作人',
  `operator_name_snapshot` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '操作人姓名快照',
  `operator_role_snapshot` varchar(256) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '操作人角色快照',
  `operation_time` datetime NOT NULL COMMENT '操作时间',
  `client_ip` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'IP',
  `user_agent` varchar(512) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT 'User-Agent',
  `reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '原因',
  `before_json` json NULL COMMENT '变更前快照',
  `after_json` json NULL COMMENT '变更后快照',
  `target_snapshot_json` json NULL COMMENT '目标对象快照',
  `success` bit(1) NOT NULL COMMENT '是否成功',
  `error_message` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误说明',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `idx_club_points_audit_log_biz_time` (`biz_type`, `biz_id`, `operation_time`) USING BTREE,
  KEY `idx_club_points_audit_log_operator_time` (`operator_user_id`, `operation_time`) USING BTREE,
  KEY `idx_club_points_audit_log_action_time` (`action_type`, `operation_time`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '业务强审计日志';

CREATE TABLE IF NOT EXISTS `club_points_job_run` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `task_type` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '任务类型',
  `biz_type` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '业务类型',
  `biz_id` bigint NULL COMMENT '业务对象 ID',
  `run_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '运行键',
  `idempotency_key` varchar(192) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '幂等键',
  `status` tinyint NOT NULL COMMENT '任务状态',
  `planned_time` datetime NULL COMMENT '计划运行时间',
  `start_time` datetime NULL COMMENT '开始时间',
  `end_time` datetime NULL COMMENT '结束时间',
  `trigger_source` tinyint NOT NULL COMMENT '触发来源：1 定时，2 手动，3 重试',
  `handler_user_id` bigint NULL COMMENT '手动处理人',
  `total_count` int NOT NULL DEFAULT 0 COMMENT '总数',
  `success_count` int NOT NULL DEFAULT 0 COMMENT '成功数',
  `skip_count` int NOT NULL DEFAULT 0 COMMENT '跳过数',
  `failed_count` int NOT NULL DEFAULT 0 COMMENT '失败数',
  `retry_count` int NOT NULL DEFAULT 0 COMMENT '已重试次数',
  `next_retry_time` datetime NULL COMMENT '下次重试时间',
  `error_type` varchar(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误类型',
  `error_message` varchar(2048) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '错误摘要',
  `result_json` json NULL COMMENT '结果详情',
  `manual_handle_reason` varchar(1024) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NULL COMMENT '人工处理说明',
  `creator` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '创建者',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '' COMMENT '更新者',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`) USING BTREE,
  UNIQUE KEY `uk_club_points_job_run_idempotency` (`idempotency_key`) USING BTREE,
  KEY `idx_club_points_job_run_task_status_planned` (`task_type`, `status`, `planned_time`) USING BTREE,
  KEY `idx_club_points_job_run_biz` (`biz_type`, `biz_id`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COLLATE = utf8mb4_unicode_ci COMMENT = '业务后台任务运行记录';
